integrations:
  gcl:
    type: dataset
    ref: paperspace/ds7me5hgjbfht6q:8ngwr2a
  poplar-executables-pyg-3-3:
    type: dataset
    ref: paperspace/dsy367uk04fig95:xcr4ic3
  pyg-cora:
    type: dataset
    ref: paperspace/dsndie6bvzw7x8n:tblwlb4
  pyg-fb15k-237:
    type: dataset
    ref: paperspace/dssixjs0cs42sys:wnuhv9b
  pyg-qm9:
    type: dataset
    ref: paperspace/dsh6w00r9u9r2x2:fiu0wlw
  pyg-reddit:
    type: dataset
    ref: paperspace/ds9uqlkb8d0t2zf:iwm985b
  pyg-tudataset:
    type: dataset
    ref: paperspace/dsdvyj7m0szchzc:pnuu29n
  ieee-fraud-detection:
    type: dataset
    ref: paperspace/ds3e21z7ahi4a71:m6nek8x
