# Copyright (c) 2022 Graphcore Ltd. All rights reserved.

_examples_internal_repository: &_examples_internal_repository
  origin: examples-internal/
  ref: null

_common_target_repository: &_common_target_repository
  origin: notebooks/
  ref: null


pyg-cluster-GCN:
  source:
    paths:
    - path: gnn/cluster_gcn/pytorch_geometric/node_classification_with_cluster_gcn.ipynb
    - path: gnn/cluster_gcn/pytorch_geometric/requirements.txt
    repository:
      <<: *_examples_internal_repository
      prefix: gnn/cluster_gcn/pytorch_geometric
  target:
    renames: {node-prediction/node_classification_with_cluster_gcn.ipynb: node-prediction/cluster_gcn_training.ipynb}
    repository:
      <<: *_common_target_repository
      prefix: node-prediction


pyg-message-passing:
  source:
    paths:
    - path: gnn/message_passing/pytorch_geometric/molecular_property_prediction_with_gin.ipynb
    - path: gnn/message_passing/pytorch_geometric/model.py
    - path: gnn/message_passing/pytorch_geometric/requirements.txt
    repository:
      <<: *_examples_internal_repository
      prefix: gnn/message_passing/pytorch_geometric
  target:
    renames: {graph-prediction/gin-molecular-prediction/molecular_property_prediction_with_gin.ipynb: graph-prediction/gin-molecular-prediction/gin_training.ipynb}
    repository:
      <<: *_common_target_repository
      prefix: graph-prediction/gin-molecular-prediction/

pyg-schnet:
  source:
    paths:
    - path: gnn/schnet/pytorch_geometric/molecular_property_prediction_with_schnet.ipynb
    - path: gnn/schnet/pytorch_geometric/utils.py
    - path: gnn/schnet/pytorch_geometric/requirements.txt
    repository:
      <<: *_examples_internal_repository
      prefix: gnn/schnet/pytorch_geometric/
  target:
    renames: {graph-prediction/schnet-molecular-prediction/molecular_property_prediction_with_schnet.ipynb: graph-prediction/schnet-molecular-prediction/schnet_training.ipynb }
    repository:
      <<: *_common_target_repository
      prefix: graph-prediction/schnet-molecular-prediction/

pyg-tgn:
  source:
    paths:
    - expression: '*'
      path: gnn/tgn/pytorch
      recursive: true
    excludes:
    - path: gnn/tgn/pytorch/README.md
    - path: gnn/tgn/pytorch/.gitignore
    - expression: '*'
      path: gnn/tgn/pytorch/.ci
      recursive: true
    repository:
      <<: *_examples_internal_repository
      prefix: gnn/tgn/pytorch
  target:
    renames: {}
    repository:
      <<: *_common_target_repository
      prefix: link-prediction/temporal-graph-networks

pyg-nbfnet-notebook:
  source:
    paths:
    - path: gnn/nbfnet/pytorch_geometric/NBFNet_training.ipynb
    - path: gnn/nbfnet/pytorch_geometric/requirements.txt
    repository:
      <<: *_examples_internal_repository
      prefix: gnn/nbfnet/pytorch_geometric
  target:
    renames: {}
    repository:
      <<: *_common_target_repository
      prefix: link-prediction/NBFNet-for-knowledge-graphs/

pyg-nbfnet-code:
  source:
    paths:
    - expression: '*'
      path: gnn/nbfnet/pytorch_geometric
      recursive: true
    excludes:
    - path: gnn/nbfnet/pytorch_geometric/NBFNet_training.ipynb
    - expression: '*'
      path: gnn/nbfnet/pytorch_geometric/.ci
      recursive: true
    repository:
      <<: *_examples_internal_repository
      prefix: gnn/nbfnet/pytorch_geometric
  target:
    renames: {}
    repository:
      <<: *_common_target_repository
      prefix: link-prediction/NBFNet-for-knowledge-graphs/nbfnet_utils/

pyg-fraud-detection:
  source:
    paths:
    - expression: '*'
      path: gnn/fraud_detection/pytorch_geometric
      recursive: true
    excludes:
    - path: gnn/fraud_detection/pytorch_geometric/README.md
    - expression: '*'
      path: gnn/fraud_detection/pytorch_geometric/.ci
      recursive: true
    - expression: '*'
      path: gnn/fraud_detection/pytorch_geometric/test
      recursive: true
    repository:
      <<: *_examples_internal_repository
      prefix: gnn/fraud_detection/pytorch_geometric
  target:
    renames: {}
    repository:
      <<: *_common_target_repository
      prefix: fraud-detection

# tutorials
pyg-1_at_a_glance:
  source:
    paths:
    - path: tutorials/tutorials/pytorch_geometric/1_at_a_glance/1_at_a_glance.ipynb
    repository:
      <<: *_examples_internal_repository
      prefix: tutorials/tutorials/pytorch_geometric/1_at_a_glance/
  target:
    renames: {}
    repository:
      <<: *_common_target_repository
      prefix: learning-pytorch-geometric-on-ipus/

pyg-2_a_worked_example:
  source:
    paths:
    - path: tutorials/tutorials/pytorch_geometric/2_a_worked_example/2_a_worked_example.ipynb
    repository:
      <<: *_examples_internal_repository
      prefix: tutorials/tutorials/pytorch_geometric/2_a_worked_example/
  target:
    renames: {}
    repository:
      <<: *_common_target_repository
      prefix: learning-pytorch-geometric-on-ipus/

pyg-3_small_graph_batching_with_padding:
  source:
    paths:
    - path: tutorials/tutorials/pytorch_geometric/3_small_graph_batching_with_padding/3_small_graph_batching_with_padding.ipynb
    repository:
      <<: *_examples_internal_repository
      prefix: tutorials/tutorials/pytorch_geometric/3_small_graph_batching_with_padding/
  target:
    renames: {}
    repository:
      <<: *_common_target_repository
      prefix: learning-pytorch-geometric-on-ipus/

pyg-4_small_graph_batching_with_packing:
  source:
    paths:
    - path: tutorials/tutorials/pytorch_geometric/4_small_graph_batching_with_packing/4_small_graph_batching_with_packing.ipynb
    repository:
      <<: *_examples_internal_repository
      prefix: tutorials/tutorials/pytorch_geometric/4_small_graph_batching_with_packing/
  target:
    renames: {}
    repository:
      <<: *_common_target_repository
      prefix: learning-pytorch-geometric-on-ipus/

pyg-5_large_graph_sampling:
  source:
    paths:
    - path: tutorials/tutorials/pytorch_geometric/5_large_graph_sampling/5_large_graph_sampling.ipynb
    repository:
      <<: *_examples_internal_repository
      prefix: tutorials/tutorials/pytorch_geometric/5_large_graph_sampling/
  target:
    renames: {}
    repository:
      <<: *_common_target_repository
      prefix: learning-pytorch-geometric-on-ipus/

pyg-6_heterogeneous_graphs:
  source:
    paths:
    - path: tutorials/tutorials/pytorch_geometric/6_heterogeneous_graphs/6_heterogeneous_graphs.ipynb
    repository:
      <<: *_examples_internal_repository
      prefix: tutorials/tutorials/pytorch_geometric/6_heterogeneous_graphs/
  target:
    renames: {}
    repository:
      <<: *_common_target_repository
      prefix: learning-pytorch-geometric-on-ipus/

pyg-tutorial-requirements:
  source:
    paths:
    - path: tutorials/tutorials/pytorch_geometric/requirements.txt
    repository:
      <<: *_examples_internal_repository
      prefix: tutorials/tutorials/pytorch_geometric/
  target:
    renames: {}
    repository:
      <<: *_common_target_repository
      prefix: learning-pytorch-geometric-on-ipus/
