# Copyright (c) 2022 Graphcore Ltd. All rights reserved.

_examples_internal_repository: &_examples_internal_repository
  origin: examples-internal/
  ref: null

_common_target_repository: &_common_target_repository
  origin: notebooks/
  ref: null


PR-template:
  source:
    paths:
    - path: .github/pull_request_template.md
      recursive: false
    excludes:
    repository:
      origin: https://github.com/graphcore/Gradient-HuggingFace
      ref: main
      prefix: .github
  target:
    repository:
      <<: *_common_target_repository
      prefix: .github
