# Copyright (c) 2022 Graphcore Ltd. All rights reserved.

_examples_internal_repository: &_examples_internal_repository
  origin: examples-internal/
  ref: null

_common_target_repository: &_common_target_repository
  origin: notebooks/
  ref: null


useful-tips:
  source:
    paths:
    - path: useful-tips
      recursive: true
    repository:
      origin: https://github.com/graphcore/Gradient-HuggingFace
      ref: main
      prefix: useful-tips
  target:
    repository:
      <<: *_common_target_repository
      prefix: useful-tips
